# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount_spent', models.FloatField(default=0.0)),
                ('date_spent', models.DateTimeField(verbose_name='date money was spent')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(verbose_name='date money was earned')),
            ],
        ),
    ]
